version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    groups:
      k8s:
        update-types:
          - patch
        patterns:
          - k8s.io/*