apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
    {{- include "konfirm.labels" . | nindent 4 }}
  name: konfirm-controller-manager-metrics-service
  namespace: konfirm-system
spec:
  ports:
  - name: https
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: https
  selector:
    control-plane: controller-manager