apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "konfirm.managerConfigMapName"  . }}
data:
  controller_manager_config.yaml: |
    apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
    kind: ControllerManagerConfig
    health:
      healthProbeBindAddress: :8081
    metrics:
      bindAddress: 127.0.0.1:8080
    webhook:
      port: 9443
    leaderElection:
      leaderElect: true
      resourceName: {{ include "konfirm.fullname" . }}.konfirm.goraft.tech
    {{- if not .Values.security.clusterOperator }}
    cacheNamespace: {{ include "konfirm.managedNamespace"  . }}
    {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{  include "konfirm.fullname" . | trunc 55 | trimSuffix "-"  }}-manager
  labels:
    control-plane: controller-manager
    {{ include "konfirm.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
      {{ include "konfirm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
        {{ include "konfirm.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - args:
        - --config=/config/controller_manager_config.yaml
        command:
        - /manager
        image: konfirm/controller:v0.1.0
        name: manager
        ports:
        - containerPort: 8080
          name: metrics
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
        volumeMounts:
          - name: manager-config
            mountPath: /config
      securityContext:
        runAsNonRoot: true
      serviceAccountName: {{ include "konfirm.serviceAccountName" . }}
      terminationGracePeriodSeconds: 10
      volumes:
        - name: manager-config
          configMap:
            name: {{ include "konfirm.managerConfigMapName" . }}
