apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: controller-manager
    {{- include "konfirm.labels" . | nindent 4 }}
  name: konfirm-manager
  namespace: konfirm-system
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
    spec:
      imagePullSecrets: {{ .Values.controller.imagePullSecrets }}
      topologySpreadConstraints: {{ .Values.controller.topologySpreadConstraints }}
      containers:
      - command:
        - /manager
        args: {{ .Values.controller.args }}
        image: "{{ .Values.controller.image }}:{{ .Values.controller.tag }}"
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.controller.health.port }}
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        ports:
        - containerPort: {{ .Values.controller.metrics.port }}
          name: metrics
        readinessProbe:
          httpGet:
            path: /readyz
            port: {{ .Values.controller.health.port }}
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          {{- toYaml .Values.controller.resources | nindent 10 }}
        securityContext:
          allowPrivilegeEscalation: false
        volumeMounts:
        - name: konfirm-manager-config
          mountPath: /controller_manager_config.yaml
          subPath: controller_manager_config.yaml
      volumes:
      - name: konfirm-manager-config
        configMap:
          name: konfirm-manager-config
      securityContext:
        runAsNonRoot: true
      serviceAccountName: {{ .Values.serviceAccount.name }}
      terminationGracePeriodSeconds: 10