
# Prometheus Monitor Service (Metrics)
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: controller-manager
spec:
  namespaceSelector:
    matchNames:
      - konfirm-system
  selector:
    matchLabels:
      control-plane: controller-manager
  podMetricsEndpoints:
    - port: metrics