# permissions for end users to view helmpolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: helmpolicy-viewer-role
rules:
- apiGroups:
  - konfirm.goraft.tech
  resources:
  - helmpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - konfirm.goraft.tech
  resources:
  - helmpolicies/status
  verbs:
  - get
