---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - konfirm.goraft.tech
  resources:
  - testruns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - konfirm.goraft.tech
  resources:
  - testruns/status
  verbs:
  - get
  - patch
- apiGroups:
  - konfirm.goraft.tech
  resources:
  - tests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - konfirm.goraft.tech
  resources:
  - tests/status
  verbs:
  - get
  - patch
- apiGroups:
  - konfirm.goraft.tech
  resources:
  - testsuites
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - konfirm.goraft.tech
  resources:
  - testsuites/status
  - testsuites/trigger
  verbs:
  - get
  - patch
