---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: konfirm-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods/finalizers
  verbs:
  - patch
- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - get
- apiGroups:
  - konfirm.goraft.tech
  resources:
  - tests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - konfirm.goraft.tech
  resources:
  - tests/finalizers
  verbs:
  - update
- apiGroups:
  - konfirm.goraft.tech
  resources:
  - tests/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - konfirm.goraft.tech
  resources:
  - testsuites
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - konfirm.goraft.tech
  resources:
  - testsuites/finalizers
  verbs:
  - update
- apiGroups:
  - konfirm.goraft.tech
  resources:
  - testsuites/status
  - testsuites/trigger
  verbs:
  - get
  - patch
  - update
