apiVersion: konfirm.goraft.tech/v1alpha1
kind: TestSuite
metadata:
  name: sample
spec:
    when:
      cron: "1-59 * * * *"
    template:
      hook:
        helm:
          name: "before-hook"
          namespace: "default"
          path: "https://github.com/kubernetes/ingress-nginx/releases/download/helm-chart-4.0.18/ingress-nginx-4.0.18.tgz"
      tests:
      - description: Generals gathered in their masses
        template:
          spec:
            containers:
              - name: test
                image: konfirm/mock:v0.1.0
      - description: Just like witches at black masses
        template:
          spec:
            containers:
              - name: test
                image: konfirm/mock:v0.1.0
      - description: Evil minds that plot destruction
        template:
          spec:
            containers:
              - name: test
                image: konfirm/mock:v0.1.0
                args:
                  - "--fail"
      - description: Sorcerer of death's construction
        template:
          spec:
            containers:
              - name: test
                image: konfirm/mock:v0.1.0
                args:
                  - "--fail"
                  - "by Black Sabbath"
