---
apiVersion: konfirm.goraft.tech/v1alpha1
kind: Test
metadata:
  name: pass
spec:
  template:
    spec:
      containers:
        - name: pass
          image: konfirm/mock:v0.1.0
          args:
            - '"This should always pass"'
---
apiVersion: konfirm.goraft.tech/v1alpha1
kind: Test
metadata:
  name: fail
spec:
  template:
    spec:
      containers:
      - name: fail
        image: konfirm/mock:v0.1.0
        args:
          - "--fail"
          - '"This should always fail"'
---
apiVersion: konfirm.goraft.tech/v1alpha1
kind: Test
metadata:
  name: fail-and-cleanup
spec:
  retentionPolicy: Never
  template:
    spec:
      containers:
      - name: fail
        image: konfirm/mock:v0.1.0
        args:
          - "--fail"
          - '"This should always fail"'
---
apiVersion: konfirm.goraft.tech/v1alpha1
kind: Test
metadata:
  name: pass-and-retain
spec:
  retentionPolicy: Always
  template:
    spec:
      containers:
      - name: pass
        image: konfirm/mock:v0.1.0
        args:
          - '"This should always pass"'
