apiVersion: konfirm.goraft.tech/v1alpha1
kind: TestSuite
metadata:
  name: sample
spec:
  retentionPolicy: Always
  setUp:
    helm:
      secret: test-suite-setup
      chartKey: chart
      valuesKey: values
  tests:
    - description: This should always pass
      retentionPolicy: OnFailure
      template:
        spec:
          containers:
            - name: pass
              image: konfirm/mock:v0.1.0
              args:
                - '"Generals gathered in their masses"'
    - description: This should pass but retain the pod
      template:
        spec:
          containers:
            - name: pass
              image: konfirm/mock:v0.1.0
              args:
                - '"Just like witches at black masses"'
    - description: This should fail and not retain the pod
      retentionPolicy: Never
      template:
        spec:
          containers:
            - name: fail
              image: konfirm/mock:v0.1.0
              args:
                - "--fail"
                - '"Evil minds that plot destruction"'
    - description: This should fail and retain the pod
      template:
        spec:
          containers:
            - name: fail
              image: konfirm/mock:v0.1.0
              args:
                - "--fail"
                - "\"Sorcerer of death's construction\""
