# Default values for konfirm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

controller:
  image: konfirm/controller
  tag: "v0.1.0"
  args: []
  pullPolicy: IfNotPresent
  replicas: 1
  imagePullSecrets: []
  health:
    port: 8081
  metrics:
    address: 127.0.0.1
    port: 8080
  webhook:
    port: 9443
  leaderElection:
    enabled: false
    resource: d5d232eb.konfirm.goraft.tech
  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 64Mi
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

service:
  port: 8443

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "konfirm-controller-manager"

monitoring: false
istio: false

