name: Go Build

on:
  workflow_dispatch:
  push:
    branches: [ "develop" ]
    tags: [*]
  pull_request:
    branches: [ "develop" ]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          cache: true
          go-version: 1.19
      - name: Install Dependencies
        run: go get .
      - name: Verify
        run: go vet ./...
  Test:
    needs: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        k8s-version: ["1.22", "1.23", "1.24", "1.25"]
    env:
      ENVTEST_K8S_VERSION: ${{ matrix.k8s-version }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          cache: true
          go-version: 1.19
      - name: Set up envtest
        run: |
          make envtest
          echo "KUBEBUILDER_ASSETS=$(bin/setup-envtest use $ENVTEST_K8S_VERSION -p path)" >> $GITHUB_ENV
      - name: Test
        run: go test ./...
  Release:
    needs: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU  # Virtualization tool 
        uses: docker/setup-qemu-action@v2
    
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push snapshot
        if: github.ref != 'refs/heads/main'
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: konfirm:${{ github.sha }}
      - name: set RELEASE_VERSION 
        if: github.ref == 'refs/heads/main'
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Build and push release
        if: env.RELEASE_VERSION != ''
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: konfirm:${{ env.RELEASE_VERSION }}
          githubOrg: rafttech