name: Go Build

on:
  push:
    branches: [ "develop", "sbom" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          cache: true
          go-version: 1.19
      - name: Install Dependencies
        run: go get .
      - name: Verify
        run: go vet ./...
  Test:
    needs: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        k8s-version: ["1.22", "1.23", "1.24", "1.25"]
    env:
      ENVTEST_K8S_VERSION: ${{ matrix.k8s-version }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          cache: true
          go-version: 1.19
      - name: Set up envtest
        run: |
          make envtest
          echo "KUBEBUILDER_ASSETS=$(bin/setup-envtest use $ENVTEST_K8S_VERSION -p path)" >> $GITHUB_ENV
      - name: Test
        run: go test ./...
  Secure:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build an image from Dockerfile
        run: |
          docker build -t konfirm:dev .
      - name: Run Trivy in GitHub SBOM mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'image'
          format: 'spdx-json'
          output: konfirm-dev.sbom.json
          image-ref: konfirm:dev
      - name: Upload SBOM to pipeline
        uses: actions/upload-artifact@v3
        with:
          name: konfirm-dev.sbom.json
          path: konfirm-dev.sbom.json
