name: Go Build

on:
  push:
    branches: [ "develop", "feature/workflows" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          cache: true
          go-version: 1.19
      - name: Install Dependencies
        run: go get .
      - name: Verify
        run: go vet ./...
  Test:
    needs: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        k8s-version: ["1.22"]
    env:
      ENVTEST_K8S_VERSION: ${{ matrix.k8s-version }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          cache: true
          go-version: 1.19
      - name: Set up envtest
        run: make envtest
      - name: env
        run: env
      - name: ls
        run: ls
      - name: Test
        run: bin/envtest use $ENVTEST_K8S_VERSION -p path
