name: Release Charts

on:
  workflow_dispatch:
  push:
    tags: ["*"]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: azure/setup-helm@v3
        name: Setup Helm
        with:
          version: 'latest'
          token: ${{ secrets.GHUB_TOKEN }} # only needed if version is 'latest'
        id: install
      - name: Package Helm Chart
        run: |
          helm package ./charts/
      - uses: actions/upload-artifact@v3
        name: Upload Helm Chart Snapshot Version
        if: startsWith(github.ref, 'refs/tags/v') != true
        with:
          name: konfirm-${{ github.sha }}.tgz
          path: konfirm*.tgz
      - name: Set env containing release tag
        if: startsWith(github.ref, 'refs/tags/v')
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - uses: actions/upload-artifact@v3
        name: Upload Helm Chart Release Version
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          name: konfirm-${{ env.RELEASE_VERSION }}.tgz
          path: konfirm*.tgz
      - name: Release with Notes
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: konfirm*.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GHUB_TOKEN }}
