name: Release Charts

on:
  workflow_dispatch:
  push:
    tags: ["*"]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set env containing release tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - uses: azure/setup-helm@v3
        name: Setup Helm
        with:
          version: 'latest'
          token: ${{ secrets.GHUB_TOKEN }} # only needed if version is 'latest'
        id: install
      - name: Package Helm Chart
        run: |
          helm package ./charts/
      - uses: actions/upload-artifact@v3
        with:
          name: konfirm-${{ env.RELEASE_VERSION }}.tgz
          path: konfirm*.tgz
