name: Test

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - uses: actions/checkout@v3
    - name: Test
      run: make test
